### ISSUE TITLE
Sorting by last updated sorts by weekday

### ISSUE THREAD

**Issue by shenef** [Avasam/speedrun.com_global_scoreboard_webapp#109]
It appears the last updated field is using a string sort which in combination with the date format in the json (Tue, 19 May 2020 03:24:00 GMT) causes the table to be sorted by the name of the weekday first.
This happens on both site versions.

Would switching the time/date format to the ISO 8601 Format (2020-05-19T12:34) be a viable option?

Mod edit:
- [x] Ensure table sorting by last-updated uses the actual date, not the formatted string
- [x] Update formatted string to be more fluent. Remove weekday and time

**Comment by Avasam** [comment]
I believe I can use the actual date object for sorting, which would work with whatever format is shown.
I prefer something that is closer to human readability, although weekday and time really isn't necessary. Especially now that the minimum time to update is a week.

- [ ] Ensure table sorting by last-updated uses the actual date, not the formatted string
- [ ] Update formatted string to be more fluent. Remove weekday and time

**Comment by Avasam** [comment]
Finally figured it out, the dates were actually string while my type system was assuming Dates all along. I simply forgot to ensure that dates are in fact dates upon fetching.
