### ISSUE TITLE
Updating an entry resets the "Show 25 entries" setting

### ISSUE THREAD

**Issue by shenef** [Avasam/speedrun.com_global_scoreboard_webapp#170]
Reproduction:
- set the amount of entries to 25
- update a runner
- Scoreboard shows only 10 entries while still showing the "25" selection in the dropdown

As far as i can tell this doesn't happen when using the 50 or 100 entry setting.

**Comment by shenef** [comment]
Closing this cause it actually just was jumping to the end of the list where it showed the last 10 entries database since, well, there weren't enough entries to show the full 25.

**Comment by Avasam** [comment]
Oh yeah, the table automatically jumps to the runner you just updated, so you don't have to go look for them.
