### ISSUE TITLE
Users with no eligible runs still get a position on the Scoreboard

### ISSUE THREAD

**Issue by shenef** [Avasam/speedrun.com_global_scoreboard_webapp#172]
The User "PizzaThePlayer" (48g0z6px) had eligible runs under the previous criteria.
But under the current criteria they apparently do not have eligible runs which gives them a 0 point entry in the Scoreboard when their entry is updated.

Update message: `User: <PizzaThePlayer, 0.0, 48g0z6px> found. Updated their entry.`

Detailed score:
![image](https://user-images.githubusercontent.com/20268890/103469353-ca88dc00-4d63-11eb-8ad2-b10e065d70b3.png)

**Comment by Avasam** [comment]
While they should disappear from the table next time you reload. The messaging isn't fully accurate and they should be removed from / shouldn't be added back to, the table after update to avoid potential confusion.

**Comment by shenef** [comment]
The entry indeed has disappeared, but only after clearing the cache and doing a hard reload. If I find another such case, I'll try to look more closely at its behavior.

**Comment by Avasam** [comment]
Fixed by bf1cc0a
![image](https://user-images.githubusercontent.com/1350584/105441360-63f63000-5c36-11eb-816c-6a32a741cad5.png)
