### ISSUE TITLE
Users with special characters are not linked to correctly

### ISSUE THREAD

**Issue by shenef** [Avasam/speedrun.com_global_scoreboard_webapp#173]
User Haru様 (18vyq58l) links to https://www.speedrun.com/user/Haru%E6%A7%98 while their correct srcom user link would be https://www.speedrun.com/user/HaruSama
No idea how they managed to change their name to that, especially without updating their URL.

**Comment by Avasam** [comment]
That's a weird one. Normally SRC users can have an international name, and a Japanese name. I ran under the assumption that the international name will always be used as the user profile URL. Which we can see, there's clearly some exception:
![image](https://user-images.githubusercontent.com/1350584/103470114-d2cd2100-4d3b-11eb-9e4f-378d615448da.png)
I don't know how I feel about adding an entire new column in the database for a very rare edge case... Not only that, but you can't even use Haru様 to update as SRC does not recognize that user. Maybe on update I could validate for a discrepancy between the name and link, and use the appropriate one? I'll see what I can do.

> No idea how they managed to change their name to that, especially without updating their URL.

It's possible a mod did it manually upon request.

However, you made me realize there's another case of bad links, see drakotou (68w934jg), where I display both their international and Japanese name:
![image](https://user-images.githubusercontent.com/1350584/103470135-335c5e00-4d3c-11eb-9f64-0030e946955e.png)
This one should be an easy fix.

**Comment by Avasam** [comment]
Interestingly enough, there might not be any japanese name left
![image](https://user-images.githubusercontent.com/1350584/103486272-a0b6d000-4dca-11eb-8e95-270761b78f87.png)

**Comment by Avasam** [comment]
More or less a patch for this one specific edge case, but essentially fixed by 12fde878dad5beb281e03f071979f664376144a5

If this comes up again I'll look for a better solution.
