### ISSUE TITLE
Adding ILs to the top 60 runs can result in a lower amount of points

### ISSUE THREAD

**Issue by shenef** [Avasam/speedrun.com_global_scoreboard_webapp#174]
Kind of a niche case but for runners with more than 60 eligible runs, that also have eligible ILs, including the ILs can lead to a smaller total of points.
That is mostly because there can be runs in the top 60 that award less points than runs out of the top 60. Even when totaling up all the ILs in the top 60, their sum can be less than the 61st run.

Example:
![image](https://user-images.githubusercontent.com/20268890/103469923-9e715900-4d6b-11eb-8d5c-ebb7f8f0d980.png)
![image](https://user-images.githubusercontent.com/20268890/103469927-a4673a00-4d6b-11eb-85ee-f0f01c9cd916.png)

I guess that can be best solved by first sorting the runs by the points they award and then deciding which runs belong into the top 60.

**Comment by Avasam** [comment]
% | Run | Pts
-- | -- | --
01 | New Super Mario Bros. - Any% (2-6) | 0.25
03 | Super Mario Galaxy - Single Stars Mario (Deep Dark Galaxy) | 0.36
10 | New Super Mario Bros. Wii - Any% (World 2) | 1.42
05 | Google Snake Game - 100 Apples (Peaceful Mode (Standard)) | 0.66
05 | Google Snake Game - 50 Apples (Peaceful Mode (Standard)) | 0.65
01 | Happy Glass - Any% (1-10) | 0.12
06 | Google Snake Game - 50 Apples (Multi Mode (Standard)) | 0.27
05 | Google Snake Game - 50 Apples (Classic Mode (Standard)) | 0.12
36 | Total | 3.85

VS

100 | New Super Mario Bros. - Cannonless | 10.43
-- | -- | --

Ah, I see what's happening here, there's not enough eligible ILs to fill in a full game run slot. So the assumption that "ILs that are worth more, relative to their weight, should go first" is still a bit too naïve.

> I guess that can be best solved by first sorting the runs by the points they award and then deciding which runs belong into the top 60.

This would result in ILs becoming irrelevant past 60 runs, which is a no go. I already take this a step further by weighing the ILs before sorting, but as you saw, that's still not enough. I'll need to make that bit of logic a tad more sophisticated.

It shouldn't have a huge effect on the rankings, but it's still very important to fix this for accuracy. Past 60* runs is the milestone where it becomes quality over quantity.

**Comment by Avasam** [comment]
FYI. Here's the helper function that takes care of sorting the top 60 runs: https://github.com/Avasam/speedrun.com_global_scoreboard_webapp/blob/8a4788a3c71c994bb3ff9e062b19d286e7e82b44/services/user_updater_helpers.py#L163-L176

**Comment by Avasam** [comment]
Fixed by ce6ae7f . Will be part of next deployment.
