### ISSUE TITLE
Favicon size can be drastically reduced

### ISSUE THREAD

**Issue by shenef** [Avasam/speedrun.com_global_scoreboard_webapp#89]
Loading the favicon seems to take up a significant portion of the first page load.

webp, 17kB, 94% smaller
https://drive.google.com/file/d/1RsRY0aLrffW-u3gcswRUncf6DYhr52do/view?usp=sharing

png, 68kB, 75% smaller
https://drive.google.com/file/d/1kKI7pZydZzKK5ab9xZ7_mKroYIegDPs-/view?usp=sharing

The webp format is currently supported by over 70% of browsers.

**Comment by Avasam** [comment]
Will be much better now thanks.
Confirmed webp favicon is working in Firefox.
![image](https://user-images.githubusercontent.com/1350584/82250832-3247ff00-991a-11ea-82d9-9115855c6d8e.png)
