### ISSUE TITLE
Loading the Scoreboard returns the entire database

### ISSUE THREAD

**Issue by shenef** [Avasam/speedrun.com_global_scoreboard_webapp#91]
https://avasam.pythonanywhere.com/api/players seems to return the whole dataset.
I'd propose to only return the selected / visible amount of entries to improve page loading speed.

**Comment by Avasam** [comment]
This is part of the entire rewriting I'm doing. Server-side pagination is one of the goals. It won't come super soon though, but I'll get there.

**Comment by Avasam** [comment]
I don't think it'll be worth spending time on this. Trying to make the entire table dynamic and losing even more on performance.
