### ISSUE TITLE
Skip requesting the User Flag when Country Code is null

### ISSUE THREAD

**Issue by shenef** [Avasam/speedrun.com_global_scoreboard_webapp#92]

**Comment by Avasam** [comment]
I think I've already done this. But not yet deployed. Will re-validate.

**Comment by Avasam** [comment]
d36059eee2b7c3bbd89a0ec76751b63b79745a4a [global-scoreboard/src/Dashboard/QuickView.tsx](https://github.com/Avasam/speedrun.com_global_scoreboard_webapp/commit/d36059eee2b7c3bbd89a0ec76751b63b79745a4a#diff-2bdc04ca86b7681a5a81cf839187e48f)

Here it is. Will be part of next release.
